# Production Profile Configuration
spring:
  jpa:
    show-sql: false

  devtools:
    restart:
      enabled: false

logging:
  level:
    root: INFO
    com.pramithamj.todo: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO

server:
  error:
    include-stacktrace: never
    include-exception: false
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: health,info
